### ISSUE TITLE
KeyPress event absent

### ISSUE THREAD

**Issue by khanalnabin** [go-p5/p5#55] opened 2021-11-11 18:38 UTC

**Comment by sbinet** [comment] 2021-11-12 08:56
duplicate of https://github.com/go-p5/p5/issues/6.

if you want to pick up the slack, there were 2 attempts at fixing this:

- https://github.com/go-p5/p5/pull/52
- https://github.com/go-p5/p5/pull/53

**Closed by sbinet** 2021-11-12 08:56 UTC
